### ISSUE TITLE
News source breaks into newline when there is no space

### ISSUE THREAD

**Issue by Pranav4399** [brettfarrow/calmernews#23]
![image](https://user-images.githubusercontent.com/28348429/195781473-5bfe3de3-9e59-45c4-bafb-e697149c5608.png)

&nbsp tag can be used to prevent news source link from breaking into a new line which makes it more readable and better looking.

**Comment by Pranav4399** [comment]
I'd be glad to do the change and open a pull request in case if the repo is open for contributions. Let me know.

**Comment by brettfarrow** [comment]
That would be great, please feel free to open a PR!

**Comment by brettfarrow** [comment]
Fixed a slightly different way in [2.4.0](https://github.com/brettfarrow/calmernews/pull/24/files) so I'm closing this issue. Thanks for the info!
